### ISSUE TITLE
IBC client still get expired

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [Stride-Labs/stride#355]
## Summary of Bug

I know that Stride relayer has updated to this https://github.com/cosmos/relayer/issues/853 to make sure that client stays alive. However, I still get error client expired when trying to ibc-transfer. 

I found this out when have to debug scripts/tests/gaia-tests.bats for proto

To make sure that what I found is correct, I have run ibc-transfer right after relayer starts and wait a long time before sending a second one.

Here is the result:

1. Right after (running)
<img width="1086" alt="Screenshot 2022-11-18 at 14 19 05" src="https://user-images.githubusercontent.com/23058164/202643982-8e4dac64-34e5-4062-bb40-3e0dd7e9026a.png">

2. After a while (expired)
<img width="641" alt="Screenshot 2022-11-18 at 13 04 35" src="https://user-images.githubusercontent.com/23058164/202644035-d30af450-d782-4838-a3d2-2fdb2efcd2f0.png">

## Version

main

## Steps to Reproduce

docker exec stride-stride1-1 strided tx ibc-transfer transfer transfer channel-0 cosmos1pcag0cj4ttxg8l7pcg0q4ksuglswuuedcextl2 3000ustrd --from val1 --chain-id STRIDE -y --keyring-backend test

run this at different time after relayer started.
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by sampocs** [comment]
Thanks for opening this @nghuyenthevinh2000! Can you confirm that you were working off a branch that's off the most updated main, and that you updated your git submodules?

Also can you share the logs in `scripts/logs/relayer-gaia.log`?

**Comment by nghuyenthevinh2000** [comment]
> Thanks for opening this @nghuyenthevinh2000! Can you confirm that you were working off a branch that's off the most updated main, and that you updated your git submodules?
> 
> Also can you share the logs in `scripts/logs/relayer-gaia.log`?

Yes, I can confirm that I am working on branch with newest update from main and I have updated my git submodules.

Here is the log file:
[relayer-gaia.txt](https://github.com/Stride-Labs/stride/files/10043894/relayer-gaia.txt)

**Comment by sampocs** [comment]
hmm, that is odd. What happens if you run with just gaia? (in `scripts/start_network.sh`, modify the `HOST_CHAINS` array so that it only has `GAIA`)
