### ISSUE TITLE
usage of bats in tests

### ISSUE THREAD

**Issue by faddat** [Stride-Labs/stride#370]
Bats is a test framework for bash.

```bash
brew install bats
```

gets us

```
Error: bats has been disabled because it has an archived upstream repository!
```

Bats repo:

https://github.com/bats-core/bats-core

install bats:

```bash
brew install bats-core
```

**Comment by sampocs** [comment]
I’m planning to add it as a submodule instead and removing brew altogether - open to other ideas though!

**Comment by nghuyenthevinh2000** [comment]
it is quite lengthly to install all bats:

```
brew tap kaos/shell
brew install bats-assert
brew install bats-file
```

https://github.com/ztombol/bats-docs#homebrew

**Comment by sampocs** [comment]
I have an open pr #374 that removes the homebrew dependency
