### ISSUE TITLE
Remove sdkerror

### ISSUE THREAD

**Issue by sampocs** [Stride-Labs/stride#371]
## Background
* Changing the ordering/numbering of sdkerrors can cause state breaking changes

## Suggested Design
* Replace sdkerrors with regular go errors

## Acceptance Criteria
* Unit and integration tests pass

**Comment by ThanhNhann** [comment]
I will handle this

**Comment by ThanhNhann** [comment]
Hey @sampocs, can you tell me more detail about the background of this issue? As an example of `cause state breaking changes`

**Comment by sampocs** [comment]
This was shared with us from osmosis devs https://github.com/osmosis-labs/osmosis/pull/2514/files

**Comment by ThanhNhann** [comment]
The change is done, plz check and merge @sampocs

**Comment by sampocs** [comment]
Deciding to stick with using sdkerrors as it still seems to be the standard - we haven't really seen other cosmos projects switching to go errors. Also, the issue that originally prompted this is easy enough to avoid (i.e. not changing the error codes in patches).
