### ISSUE TITLE
Move MsgServer to attribute in KeeperTestSuite (remove GetMsgServer)

### ISSUE THREAD

**Issue by sampocs** [Stride-Labs/stride#544]
## Background
`x/stakeibc/keeper/keeper_test.go` defines a `KeeperTestSuite` with a `GetMsgServer` function. I can't remember why a Getter was used for this and I don't think it's necessary.

## Suggested Design
In `x/stakeibc/keeper/keeper_test.go`, change this:
```go
type KeeperTestSuite struct {
	apptesting.AppTestHelper
}

func (s *KeeperTestSuite) SetupTest() {
	s.Setup()
}

func (s *KeeperTestSuite) GetMsgServer() types.MsgServer {
	return keeper.NewMsgServerImpl(s.App.StakeibcKeeper)
}
```
To this:
```go
type KeeperTestSuite struct {
	apptesting.AppTestHelper
        MsgServer types.MsgServer
}

func (s *KeeperTestSuite) SetupTest() {
	s.Setup()
        s.MsgServer = keeper.NewMsgServerImpl(s.App.StakeibcKeeper)
}
```
And update unit tests appropriately
```go
_, err := s.GetMsgServer().LiquidStake(sdk.WrapSDKContext(s.Ctx), &msg)
// changed to
_, err := s.MsgServer.LiquidStake(sdk.WrapSDKContext(s.Ctx), &msg)
```

## Acceptance Criteria
* Unit tests pass

**Comment by hoangdv2429** [comment]
Can I handle this ?

**Comment by sampocs** [comment]
Go for it! Thanks for checking first :)

**Comment by hoangdv2429** [comment]
@sampocs Can you have a look ? Thank you!

**Comment by sampocs** [comment]
After discussion [here](https://github.com/Stride-Labs/stride/pull/555#discussion_r1061667970), decision was made to leave this as is
