### ISSUE TITLE
Unbonding records of amount zero should be deleted every epoch, but it is not deleted.

### ISSUE THREAD

**Issue by gloryan0829** [Stride-Labs/stride#609]
## Summary of Bug
 - Unbonding record of amount zero among unbonding records should be deleted every epoch, but it is not deleted.
 - The problem code is below ( x/stakeibc/keeper/unbonding_records.go )
 - I think it will be caused the performance issue because it doesn't remove unbonding record even though it has zero unbonding amount. you can check the snapshot below
 - the problem code is below and please check ISSUE CODE comment
 
   ```
        // Deletes any epoch unbonding records that have had all unbondings claimed
        func (k Keeper) CleanupEpochUnbondingRecords(ctx sdk.Context, epochNumber uint64) bool {
	        k.Logger(ctx).Info("Cleaning Claimed Epoch Unbonding Records...")
        
	        for _, epochUnbondingRecord := range k.RecordsKeeper.GetAllEpochUnbondingRecord(ctx) {
		        shouldDeleteEpochUnbondingRecord := true
		        hostZoneUnbondings := epochUnbondingRecord.HostZoneUnbondings
        
		        for _, hostZoneUnbonding := range hostZoneUnbondings {
			        // if an EpochUnbondingRecord has any HostZoneUnbonding with non-zero balances, we don't delete the EpochUnbondingRecord
			        // because it has outstanding tokens that need to be claimed
                                // ISSUE CODE
			        if hostZoneUnbonding.NativeTokenAmount != sdkmath.ZeroInt() { // 0 != 0 -> output >> true 
				        shouldDeleteEpochUnbondingRecord = false
				        break
			        }
		        }
		        if shouldDeleteEpochUnbondingRecord {
			        k.Logger(ctx).Info(fmt.Sprintf("  EpochUnbondingRecord %d - All unbondings claimed, removing record", epochUnbondingRecord.EpochNumber))
			        k.RecordsKeeper.RemoveEpochUnbondingRecord(ctx, epochUnbondingRecord.EpochNumber)
		        } else {
			        k.Logger(ctx).Info(fmt.Sprintf("  EpochUnbondingRecord %d - Has unclaimed unbondings", epochUnbondingRecord.EpochNumber))
		}
	   }

	    return true
        }
   ```

- This conditional statement above does not work as intended. If you want to do as you intended, you have to do as follows I think.

   ```
     if !hostZoneUnbonding.NativeTokenAmount.Equal(sdk.ZeroInt()) { // 0 != 0 -> output >> false 
				shouldDeleteEpochUnbondingRecord = false
				break
			}
   ```

## Version

v5.1.1 ( `3e0f4045` )

## Screenshots
 - Let's assume that current epoch number is STRIDE EPOCH #4817
 - Many empty records are existed. It could be caused a performance issue
<img width="736" alt="image" src="https://user-images.githubusercontent.com/27390552/217442415-ff2e0857-8b75-46ed-b8bb-45fcda54a091.png">

## Additional context
 - `UserRedemptionRecordForUser` function also need to be changed.
     (x/records/keeper/grpc_query_user_redemption_record_for_user.go) 

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by gloryan0829** [comment]
I just tried to push a branch for bug fix. it needs to be granted for repo push, though. May I get the permission?

**Comment by sampocs** [comment]
Great catch! Can you create a fork and open a PR from your fork?

**Comment by gloryan0829** [comment]
> Great catch! Can you create a fork and open a PR from your fork?

Next time, I'll do PR after forking this repo!!
